meta_product_name: "Michael the Maker"
meta_title: "Michael the Maker"
meta_description: "Educator | Maker | Fullstack Developer"
meta_image: "coding.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
